FROM python:3.12-slim

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

WORKDIR /app

# Встановлюємо системні залежності для psycopg2
RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Копіюємо вимоги та встановлюємо Python залежності
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Копіюємо весь проект
COPY . /app/

# Робимо скрипт entrypoint виконуваним
RUN chmod +x entrypoint.sh

# Збираємо статичні файли
RUN python manage.py collectstatic --noinput

EXPOSE 8000

# Використовуємо entrypoint скрипт
ENTRYPOINT ["./entrypoint.sh"]