FROM python:3.12-slim

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV PORT=8000
ENV DJANGO_SETTINGS_MODULE=group_project.settings

WORKDIR /app

# Встановлюємо системні залежності
RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Копіюємо вимоги та встановлюємо Python залежності
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Копіюємо весь проект
COPY . /app/

# Збираємо статичні файли
RUN python manage.py collectstatic --noinput

EXPOSE 8000

# Використовуємо JSON формат для CMD
CMD ["sh", "-c", "python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn group_project.wsgi:application --bind 0.0.0.0:$PORT"]