# Generated by Django 5.2.8 on 2026-02-13 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('file', models.FileField(upload_to='gallery/')),
                ('media_type', models.CharField(choices=[('screenshot', 'Скріншот'), ('meme', 'Мем'), ('clip', 'Кліп'), ('other', 'Інше')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
