# Generated by Django 5.2.8 on 2026-02-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('configs', 'Конфіги (cfg-файли)'), ('guides', 'Гайди'), ('tutorials', 'Відеоуроки'), ('training', 'Тренування aim/recoil'), ('demos', 'Демки з турнірів')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='materials/')),
                ('link', models.URLField(blank=True, null=True)),
                ('youtube_embed', models.TextField(blank=True, help_text='HTML код для вбудовування YouTube')),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
