# Generated by Django 5.2.8 on 2026-02-13 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('item_type', models.CharField(choices=[('screenshot', 'Скріншот'), ('demo', 'Демо'), ('video', 'Відео'), ('highlight', 'Хайлайт')], max_length=20)),
                ('file', models.FileField(upload_to='portfolio/')),
                ('role', models.CharField(blank=True, choices=[('rifler', 'Rifler'), ('awper', 'AWPer'), ('lurker', 'Lurker'), ('support', 'Support'), ('igl', 'IGL (In-Game Leader)'), ('entry', 'Entry Fragger')], max_length=20)),
                ('game_map', models.CharField(blank=True, help_text='Карта на якій зроблено хайлайт', max_length=50)),
                ('weapon', models.CharField(blank=True, help_text='Зброя, яка була використана', max_length=50)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
